### ISSUE TITLE
Breaks in Chrome

### ISSUE THREAD

**Issue by mstnorris** [wilddeer/stickyfill#28]
```css
.navbar-sub {
    position: -webkit-sticky;
    position: sticky;
    top: 50px;
    z-index: 1000;
}

.navbar-sub:before,
.navbar-sub:after {
    content: '';
    display: table;
}
```

The above code causes Chrome to freak out.
