### ISSUE TITLE
adds whitespace when printing webpage in IE

### ISSUE THREAD

**Issue by bruffridge** [wilddeer/stickyfill#70]
I had to add the following css to hide the div added by stickyfill, which caused whitespace to appear at the top of the page. Just thought I'd share in case it helps someone else with the same issue.

```css
// fixes IE whitespace at top of first page print bug caused by stickyfill polyfill.
@media print and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  .sticky + div[style] {
    display: none;
  }
}
```
